version: "3.9"
services:
  server:
    container_name: server
    image: caophuoclongse/chatappserver:1.0.0
    ports:
      - "3003:3003"
    volumes:
      - ./backend:/app
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql
      - NODE_ENV=production
    depends_on:
      - mysql
      - redis
  client:
    container_name: client
    image: caophuoclongse/chatappclient:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
      - REACT_APP_SERVER_URL=https://api.bebes.site
      - REACT_APP_WS_URL=wss://api.bebes.site
  admin:
    container_name: phpadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=516489C@k
    depends_on:
      - mysql
      - server
  mysql:
    container_name: mysql
    user: root
    image: mysql
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: 516489C@k
      MYSQL_DATABASE: chatapp
      MYSQL_USER: user
      MYSQL_PASSWORD: 516489
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./ssl:/etc/nginx/ssl
