version: '3.9'
services:
  # server:
  #   image: server
  #   build: ./backend
  #   container_name: server
  #   ports:
  #     - 3003:3003
  #   volumes:
  #     - ./test123:/app

  #     # - ./env/server.env:/app/.env
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=mysql
  #     - DB_USER=root
  #     - DB_PASSWORD=516489
  #     - DB_NAME=chatapp
  #     - JWT_SECRET=caophuoclong123123123
  #     - PEPPER=caophuoclong26032001
  #     - EXPIRE_TOKEN_TIME=1d
  #     - REDIS_HOST=redis
  #     - REDIS_PASSWORD=516489
  #   # depends_on:
  #   #   - mysql
  #   #   - redis
  # client:
  #   image: client
  #   build: ./frontend
  #   container_name: client
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./frontend:/app
  #     # - ./env/client.env:/app/.env
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - server
  mysql:
    container_name: mysql
    user: root
    image: mysql
    restart: 'always'
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 516489C@k
      MYSQL_DATABASE: chatapp
      MYSQL_USER: user
      MYSQL_PASSWORD: 516489
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      # - ./nginx/ssl:/etc/nginx/ssl