version: '3.9'
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql
    user: root
    image: mysql
    restart: 'always'
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 516489C@k
      MYSQL_DATABASE: chatapp
      MYSQL_USER: user
      MYSQL_PASSWORD: 516489
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./public:/var/www/html
    depends_on:
      - app